dolt.database: "pushbullet_chrome_extension"
dolt.host: "doltsrv.lan"
dolt.port: 3307
dolt.user: "root"
backup.enabled: false
dolt.auto-push: false
export.auto: false

sync.remote: "http://doltsrv.lan:50051/chuck/pushbullet-chrome-extension"